#pragma once

using namespace ATL;

template <class T>
class CProxy_IBinaryFileEvents : public IConnectionPointImpl<T, &__uuidof( _IBinaryFileEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
